# Generated by Django 6.0.4 on 2026-07-26 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='förnamn')),
                ('last_name', models.CharField(max_length=80, verbose_name='efternamn')),
                ('phone', models.CharField(max_length=40, verbose_name='telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='e-post')),
                ('date', models.DateField(verbose_name='datum')),
                ('time', models.TimeField(verbose_name='tid')),
                ('guests', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)], verbose_name='antal gäster')),
                ('message', models.TextField(blank=True, verbose_name='meddelande')),
                ('whatsapp_sent', models.BooleanField(default=False, verbose_name='WhatsApp skickat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='skapad')),
            ],
            options={
                'verbose_name': 'bokning',
                'verbose_name_plural': 'bokningar',
                'ordering': ['-created_at'],
            },
        ),
    ]
