# Generated by Django 6.1.1 on 2026-09-13 23:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='förnamn')),
                ('last_name', models.CharField(max_length=80, verbose_name='efternamn')),
                ('phone', models.CharField(max_length=40, verbose_name='telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='e-post')),
                ('preferred_date', models.DateField(blank=True, null=True, verbose_name='önskat datum')),
                ('guests', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='ungefärligt antal gäster')),
                ('occasion', models.CharField(blank=True, help_text='Fritext — inventera inte paketlistor i UI utan bekräftat innehåll.', max_length=120, verbose_name='typ av tillställning')),
                ('message', models.TextField(blank=True, verbose_name='meddelande')),
                ('notify_sent', models.BooleanField(default=False, verbose_name='notifiering skickad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='skapad')),
            ],
            options={
                'verbose_name': 'eventförfrågan',
                'verbose_name_plural': 'eventförfrågningar',
                'ordering': ['-created_at'],
            },
        ),
    ]
