# Generated by Django 5.1.15 on 2026-09-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_menyredaktor_gallery_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryphoto',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Avmarkera för att dölja fotot på webbplatsen. Nya uppladdningar startar opublicerade.'),
        ),
    ]
