# Generated by Django 6.0.7 on 2026-08-02 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LunchWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Valfri dag i veckan — sparas som måndagen i den ISO-veckan.')),
                ('year', models.PositiveIntegerField(editable=False)),
                ('week_number', models.PositiveIntegerField(editable=False)),
                ('intro_text', models.TextField(blank=True, help_text='Valfri introtext. Tom = webbplatsen använder standardtexten.')),
                ('notes', models.TextField(blank=True, help_text='T.ex. vad som ingår (sallad, bröd, kaffe) eller öppettider för lunch.')),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'lunchvecka',
                'verbose_name_plural': 'lunchveckor',
                'ordering': ['-year', '-week_number'],
                'constraints': [models.UniqueConstraint(fields=('year', 'week_number'), name='unique_lunch_week_year_week')],
            },
        ),
        migrations.CreateModel(
            name='LunchDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Måndag'), (1, 'Tisdag'), (2, 'Onsdag'), (3, 'Torsdag'), (4, 'Fredag'), (5, 'Lördag'), (6, 'Söndag')], help_text='Tom = övrigt / gäller hela veckan (t.ex. soppa, sallad).', null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_available', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('lunch_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='lunch.lunchweek')),
            ],
            options={
                'verbose_name': 'lunchrätt',
                'verbose_name_plural': 'lunchrätter',
                'ordering': ['weekday', 'order', 'id'],
            },
        ),
    ]
