# Generated by Django 6.0.7 on 2026-08-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0002_menyredaktor_lunch_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunchweek',
            name='skip_auto_sync',
            field=models.BooleanField(default=False, help_text='Om ikryssad uppdateras inte denna vecka av den dagliga Mat och Mat-synken.'),
        ),
        migrations.AlterField(
            model_name='lunchdish',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
