# Generated by Django 5.1.15 on 2026-09-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuratedReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(verbose_name='citat')),
                ('author_name', models.CharField(max_length=120, verbose_name='namn')),
                ('source', models.CharField(help_text='t.ex. Google, gästbok — måste vara verklig källa.', max_length=80, verbose_name='källa')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Lämna tomt om inget betyg finns från källan.', null=True, verbose_name='betyg (1–5)')),
                ('is_published', models.BooleanField(default=False, verbose_name='publicerad')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'omdöme',
                'verbose_name_plural': 'omdömen',
                'ordering': ['order', '-id'],
            },
        ),
    ]
