# Generated by Django 6.0.4 on 2026-07-27 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Valfri dag i veckan — sparas som måndagen i den ISO-veckan.')),
                ('year', models.PositiveIntegerField(editable=False)),
                ('week_number', models.PositiveIntegerField(editable=False)),
                ('intro_text', models.TextField(blank=True, help_text='Valfri introtext. Tom = webbplatsen använder standardtexten.')),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'veckans erbjudande',
                'verbose_name_plural': 'veckans erbjudanden',
                'ordering': ['-year', '-week_number'],
                'constraints': [models.UniqueConstraint(fields=('year', 'week_number'), name='unique_weekly_offer_year_week')],
            },
        ),
        migrations.CreateModel(
            name='OfferDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_available', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='offers.weeklyoffer')),
            ],
            options={
                'verbose_name': 'rätt',
                'verbose_name_plural': 'rätter',
                'ordering': ['order', 'id'],
            },
        ),
    ]
