# Generated by Django 5.1.15 on 2026-09-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningHoursDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Måndag'), (1, 'Tisdag'), (2, 'Onsdag'), (3, 'Torsdag'), (4, 'Fredag'), (5, 'Lördag'), (6, 'Söndag')], unique=True)),
                ('opens', models.TimeField(blank=True, null=True)),
                ('closes', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False, help_text='Om True är dagen stängd (opens/closes ignoreras).')),
            ],
            options={
                'verbose_name': 'öppettidsdag',
                'verbose_name_plural': 'öppettidsdagar',
                'ordering': ['weekday'],
            },
        ),
        migrations.CreateModel(
            name='OpeningHoursSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='Europe/Stockholm', max_length=64)),
                ('max_guests_online', models.PositiveIntegerField(default=6)),
                ('slot_interval_minutes', models.PositiveIntegerField(default=30)),
            ],
            options={
                'verbose_name': 'öppettider-inställningar',
                'verbose_name_plural': 'öppettider-inställningar',
            },
        ),
    ]
