"""
Django settings for Raffaello Restaurang.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')

SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv('DEBUG', 'False') == 'True'

if not SECRET_KEY:
    raise ImproperlyConfigured(
        'SECRET_KEY is not set. Copy backend/.env.example to backend/.env '
        'or define SECRET_KEY in backend/.env.'
    )

_allowed_raw = os.getenv('ALLOWED_HOSTS', 'localhost').split(',')
ALLOWED_HOSTS = [h.strip() for h in _allowed_raw if h.strip()]
# Docker / Compose healthchecks call 127.0.0.1; public .env often lists only the domain.
if '*' not in ALLOWED_HOSTS:
    for _loopback in ('127.0.0.1', 'localhost'):
        if _loopback not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(_loopback)
# Host header includes the port; plain "localhost" does not match "localhost:5173".
if DEBUG and '*' not in ALLOWED_HOSTS:
    for _dev_host in (
        '127.0.0.1:8000',
        'localhost:8000',
        '127.0.0.1:5173',
        '127.0.0.1:5174',
        'localhost:5173',
        'localhost:5174',
    ):
        if _dev_host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(_dev_host)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'menu',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'raffaello.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'raffaello.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

_db_name = os.getenv('DB_NAME')
_db_user = os.getenv('DB_USER')
_db_password = os.getenv('DB_PASSWORD')
if not _db_name or not _db_user:
    raise ImproperlyConfigured(
        'DB_NAME and DB_USER must be set in backend/.env. '
        'See backend/.env.example and scripts/create_local_database.sql.'
    )

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': _db_name,
        'USER': _db_user,
        'PASSWORD': _db_password or '',
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'sv'

TIME_ZONE = 'Europe/Stockholm'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

CORS_ALLOWED_ORIGINS = [
    o.strip()
    for o in os.getenv(
        'CORS_ALLOWED_ORIGINS',
        'http://localhost:5173,http://localhost:5174,'
        'http://127.0.0.1:5173,http://127.0.0.1:5174',
    ).split(',')
    if o.strip()
]

CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.getenv(
        'CSRF_TRUSTED_ORIGINS',
        'http://localhost:5173,http://localhost:5174,'
        'http://127.0.0.1:5173,http://127.0.0.1:5174',
    ).split(',')
    if o.strip()
]

# HTTPS behind reverse proxy (nginx sets X-Forwarded-Proto). Required for admin/CSRF over TLS.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# HSTS: set SECURE_HSTS_SECONDS in .env after confirming HTTPS works end-to-end (e.g. 31536000).
_hsts_seconds = int(os.getenv('SECURE_HSTS_SECONDS', '0') or '0')
if not DEBUG and _hsts_seconds > 0:
    SECURE_HSTS_SECONDS = _hsts_seconds
    SECURE_HSTS_INCLUDE_SUBDOMAINS = (
        os.getenv('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True') == 'True'
    )
    SECURE_HSTS_PRELOAD = os.getenv('SECURE_HSTS_PRELOAD', 'False') == 'True'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
