# Generated by Django 5.1.15 on 2026-09-13 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menu_editor_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='allergens',
            field=models.CharField(blank=True, help_text='Kommaseparerat. Visa endast om ifyllt av personal.', max_length=255, verbose_name='allergener'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Valfri rättbild. Tom = ingen bild i UI.', null=True, upload_to='menu/', verbose_name='bild'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Prioriteras i startsidans signaturrätter när markerad.', verbose_name='utvald (startsida)'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='tags',
            field=models.CharField(blank=True, help_text='t.ex. Signature, Populär — kommaseparerat.', max_length=255, verbose_name='etiketter'),
        ),
    ]
